support non-controlling terminals
judah/haskeline pull request #156
Opened 2021-03-11 20:39 UTC by goertzenator

This patch adds `useTermHandles` to support terminals other than the controlling terminal.  For example, opening and serving a serial port might look like...

``` Haskell
main :: IO ()
main = do
  behavior <- useTermHandles (Just "vt100")
    <$> openFile "/dev/ttyUSB0" ReadMode
    <*> openFile "/dev/ttyUSB0" WriteMode
  runInputTBehavior behavior defaultSettings loop
    where
      loop :: InputT IO ()
      loop = do ...
```
This also has applications for pseudo terminals as per issue #147.

Testing:
- I was unable to run the tests on my machine.
- I am running this code on a hardware serial port and it seems to work fine.

2021-03-22 13:57 UTC, goertzenator commented
Some comments on a Windows implementation:

This PR does not implement `useTermHandles` for Windows.  I tried briefly to port the changes into the Windows backend, but more rework is required there than I was comfortable with so I abandoned the effort.  I think it would be useful to do that at some point; being able to support serial ports and the new ConPTY under Windows would be a good thing.

I would urge that this PR be merged despite the lack of Windows support.  It would be useful to me and likely others.  What I do seek though is the input of a Windows expert to determine if the new API `useTermHandles` is going to be suitable for Windows.  That at least should be made portable so that a Window implementation can later be merged.

2021-05-04 07:02 UTC, NorfairKing commented
+1 Just subscribing.

2026-05-07 13:44 UTC, goertzenator commented
Some TLC was applied to this PR
- Rebased to current master.
- Term parameter removed, functionality split into two functions "`useTermHandles`" and "`useTermHandlesWith`".
- Added documentation.
- Added tests.

Example from the new docs to illustrate what this PR is about:

```
-- ==== __Example: a Haskeline session on a serial port__
--
-- > import System.IO (withFile, IOMode(..))
-- > import System.Console.Haskeline
-- >
-- > serialUI :: FilePath -> IO ()
-- > serialUI devPath =
-- >     withFile devPath ReadMode  $ \input  ->
-- >     withFile devPath WriteMode $ \output ->
-- >         runInputTBehavior (useTermHandlesWith "vt100" input output)
-- >                           defaultSettings
-- >                           loop
-- >   where
-- >     loop = do
-- >         minput <- getInputLine "% "
-- >         case minput of
-- >             Nothing     -> return ()
-- >             Just "quit" -> return ()
-- >             Just s      -> outputStrLn ("got: " ++ s) >> loop
```

I still use this feature in my app and would still love to see it merged here.

2026-05-07 13:51 UTC, athas requested changes
I'm not opposed to merging this if CI succeeds. Looks like the current failures are just the usual business with ancient GHCs.

Could you also add a mention to the CHANGELOG? My understanding is that this change does not affect any existing behaviour, but we should still mention new (Windows-only?) functionality.

2026-05-07 14:47 UTC, goertzenator commented
Thank you for your prompt response.  I fixed the (<>) issue on ancient ghc, added a changelog, and updated the example to a much more relevant websocket/pty example (below).

I see a change request note above, but clicking on it doesn't show anything.  I don't have anything more to add to this PR unless you had something else.

Thanks again.


```
-- ==== __Example: a Haskeline session over a WebSocket__
--
-- Bridge a WebSocket to the master end of a PTY pair and run Haskeline
-- against the slave end.  Uses the @websockets@ and @unix@ packages.
-- Pair this with a browser-side terminal emulator such as
-- <https://xtermjs.org/ Xterm.js> for an in-browser shell.
--
-- > import qualified Network.WebSockets as WS
-- > import System.Posix.Terminal (openPseudoTerminal)
-- > import System.Posix.IO (dup, fdToHandle)
-- > import Control.Applicative ((<|>))
-- > import Control.Concurrent.Async (Concurrently(..), runConcurrently)
-- > import Control.Monad (forever)
-- > import qualified Data.ByteString as BS
-- > import System.IO (hSetBuffering, BufferMode(..))
-- > import System.Console.Haskeline
-- >
-- > websocketUI :: WS.Connection -> IO ()
-- > websocketUI conn = do
-- >     (master, slave) <- openPseudoTerminal
-- >     slaveDup <- dup slave
-- >     masterH  <- fdToHandle master
-- >     slaveIn  <- fdToHandle slave
-- >     slaveOut <- fdToHandle slaveDup
-- >     hSetBuffering masterH NoBuffering
-- >     -- Whichever of the three actions finishes first cancels the others.
-- >     runConcurrently
-- >         $   Concurrently (forever $ WS.receiveData conn >>= BS.hPut masterH)
-- >         <|> Concurrently (forever $ BS.hGetSome masterH 4096 >>= WS.sendBinaryData conn)
-- >         <|> Concurrently (runInputTBehavior
-- >                              (useTermHandlesWith "vt100" slaveIn slaveOut)
-- >                              defaultSettings loop)
-- >   where
-- >     loop = do
-- >         minput <- getInputLine "% "
-- >         case minput of
-- >             Nothing     -> return ()
-- >             Just "quit" -> return ()
-- >             Just s      -> outputStrLn ("got: " ++ s) >> loop
```

2026-05-07 17:38 UTC, athas commented
I have no further requests for changes.

2026-05-07 17:59 UTC, merged